## You should change each of the following fields
## to customize your blog

title: Calculating Basic Descriptive Statistics in Python
description: This is a basic tutorial for effectively using Python to calculate summary statistics from data. 
author: Everett Andrew
author_description: I'm a student studying Statistics at BYU. This is my first blog post!

url: https://evandrewer.github.io ## change this to https://yourusername.github.io
baseurl: /my-blog  ## change this to the name of your blog repository
header_image: /assets/img/headerimg.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  evandrewer
    twitter: 
    facebook: 
    email: 
    linkedin: 
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




